package:
  name: python-pygaze
  version: "0.6.0a25"

source:
  fn: python-pygaze-0.6.0a25.tar.gz
  url: https://pypi.python.org/packages/7d/9b/053c15bae5b2211d1264c08bb9a8f1f642a5231137c2de4e64579768e866/python-pygaze-0.6.0a25.tar.gz
  md5: c56d3910df6ed776191e7a41c2321d2b

build:
  noarch_python: True
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pygaze
    - pygaze._display
    - pygaze._eyetracker
    - pygaze._joystick
    - pygaze._keyboard
    - pygaze._logfile
    - pygaze._misc
    - pygaze._mouse
    - pygaze._screen
    - pygaze._sound
    - pygaze._time
    - pygaze.plugins

about:
  home: http://www.pygaze.org/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'A Python library for eye tracking'

