package:
  name: python-pygaze
  version: "0.6.0a15"

source:
  fn: python-pygaze-0.6.0a15.tar.gz
  url: https://pypi.python.org/packages/7e/39/5d16199157d791be205ee0a5112d11d7a167347c154be1a907b1dc23574a/python-pygaze-0.6.0a15.tar.gz
  md5: ca8919d04d86d75735f7210b874ddd1e

build:
  noarch_python: True
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pygaze
    - pygaze._display
    - pygaze._eyetracker
    - pygaze._joystick
    - pygaze._keyboard
    - pygaze._logfile
    - pygaze._misc
    - pygaze._mouse
    - pygaze._screen
    - pygaze._sound
    - pygaze._time
    - pygaze.plugins

about:
  home: http://www.pygaze.org/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'A Python library for eye tracking'

