{% set name = "python-pygaze" %}
{% set version = "0.7.1" %}
{% set sha256 = "e277d55cbe12dfc4d48333696e3e8b9fff0e549ec273fda3add69e8999d10295" %}
{% set url = "https://files.pythonhosted.org/packages/c0/ee/d0d03bcf036d82b104a04eb8ec46db95dcb2d826944e1cf76ee4f91d05cf/python-pygaze-0.7.1.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pygaze
    - pygaze._display
    - pygaze._eyetracker
    - pygaze._joystick
    - pygaze._keyboard
    - pygaze._logfile
    - pygaze._misc
    - pygaze._mouse
    - pygaze._screen
    - pygaze._sound
    - pygaze._time
    - pygaze.plugins

about:
  home: http://www.pygaze.org/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'A Python library for eye tracking'
