package:
  name: python-qnotifications
  version: "1.1.0"

source:
  git_rev: v1.1.0
  git_url: https://github.com/dschreij/QNotifications.git

build:
  noarch_python: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyqt
    - qt
    - qtpy

  run:
    - python
    - qtpy
    - qt
    - pyqt

test:
  # Python imports
  imports:
    - QNotifications

about:
  home: https://github.com/dschreij/QNotifications
  license: GNU General Public License v3 (GPLv3)
  license_file: copyright
  summary: 'Web-style in-app notifications for PyQt4/5'
