{% set name = "python-qnotifications" %}
{% set version = "2.0.3" %}

package:
  name: {{ name }}
  version: {{ version}}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/dschreij/QNotifications.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 2

requirements:
  build:
    - python=3.6.4=0
    - setuptools
    - qtpy=1.4.0  
    - pyqt
    - qt

  run:
    - python
    - qtpy
    - pyqt

test:
  # Python imports
  imports:
    - QNotifications

about:
  home: https://github.com/dschreij/QNotifications
  license: GNU General Public License v3 (GPLv3)
  license_file: copyright
  summary: 'Web-style in-app notifications for PyQt4/5'
