{% set name = "rapunzel" %}
{% set version = "0.4.5" %}
{% set sha256 = "4b969619d4f980a6f79d607dd4c0e6738fb574daa7aa27557e1e6380bc880105" %}
{% set url = "https://files.pythonhosted.org/packages/0f/af/bf6309ab68a61ed7d4f65947da53e7b59c3b712f2e89e43468784ca77e2e/rapunzel-0.4.5.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel
  ignore_run_exports:
    - python_abi    

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.0
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
