{% set name = "rapunzel" %}
{% set version = "0.3.0" %}
{% set sha256 = "9d7abbcd5502e20f2ad8221696bf16d8bc4ba31e266d9b9e5b4642f6b268ca34" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/18/55/245891eb8ef6a9b8476f54ed71bfde1fcb058f7d93dfe1161417a26da987/rapunzel-0.3.0.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel

requirements:
  build:
    - python
    - python-opensesame >=3.3.0a29
    - python-levenshtein
    - qtconsole
    - nbformat

  run:
    - python
    - python-opensesame >=3.3.0a29
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
