{% set name = "rapunzel" %}
{% set version = "0.4.6" %}
{% set sha256 = "88d3c864dc336040eae9548f81005f782f75caf6eced356dd5ee796c8015646d" %}
{% set url = "https://files.pythonhosted.org/packages/1c/1f/36a737b6c6ee5c752b2b2b41b6f3a6b7c1d29db250bb580bfdbd53073cee/rapunzel-0.4.6.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel
  ignore_run_exports:
    - python_abi    

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.0
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
