{% set name = "rapunzel" %}
{% set version = "0.3.14" %}
{% set sha256 = "f5a7f5bc029e97340a59aeab044584ff654896f8ed576fa008ae07e73eb04a6b" %}
{% set url = "https://files.pythonhosted.org/packages/2c/85/feea9cedd285b06e0f2e0d9c85c7cf9a6123cd225ce8923afcb1808e3d82/rapunzel-0.3.14.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.0a40
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
