{% set name = "rapunzel" %}
{% set version = "0.3.6" %}
{% set sha256 = "70a5f80b94259741b32eb7dee5544bb2e08a4d5337ddab582d225d569b9163f5" %}
{% set url = "https://files.pythonhosted.org/packages/ca/6c/b2f43cbeeeca982d1f152c3feec7eadd0cd97156ce8ab2f39a1f2a37741b/rapunzel-0.3.6.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.0a33
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
