{% set name = "rapunzel" %}
{% set version = "0.3.13" %}
{% set sha256 = "df2a1b1d260792562d26651390c531c04779fa465a4a55787a26532d66b2b005" %}
{% set url = "https://files.pythonhosted.org/packages/ad/ed/80136d54bfaa09edfc128e7424d0e8dc9c12aeb69fe33077e76ff087aa61/rapunzel-0.3.13.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.0a40
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
