{% set name = "rapunzel" %}
{% set version = "0.3.5" %}
{% set sha256 = "f0ad11cbb0fa7f8bef73e790e3665461f64e40b3306cfc5eb7cdc511a9d411a3" %}
{% set url = "https://files.pythonhosted.org/packages/fc/f7/422c73c58ce3dade21eccfe755dae973caa544052a1ec9f687eaae249aec/rapunzel-0.3.5.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.0a33
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
