{% set name = "rapunzel" %}
{% set version = "0.3.31" %}
{% set sha256 = "486d624ea818f2c89b6d9144e3d26338750db1a9a4c011d79d324515b87f6a57" %}
{% set url = "https://files.pythonhosted.org/packages/71/2b/55d8c7ec9918bf87ae7af312247e42b68411e05704eae709ce8cf8a833e7/rapunzel-0.3.31.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - rapunzel = rapunzel:rapunzel

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame >=3.3.0a47
    - python-levenshtein
    - qtconsole
    - nbformat
    - pyspellchecker

about:
  home: https://github.com/smathot/rapunzel
  license: GNU General Public License v3 (GPLv3)
  summary: A modern code editor for Python and R

app:
  entry: rapunzel
  icon: rapunzel.png
  summary: A modern code editor for Python and R
