{% set name = "pyqode.python" %}
{% set version = "2.12.2a6" %}
{% set sha256 = "5b2462081a50e4e9b2d2eb32a8b8e536a8fc16502ad7c69d187899864721c5a7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.cogsci.nl/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - docutils
    - jedi
    - pycodestyle
    - pip
    - pyflakes
    - pyqode.core
    - pyqode.qt
    - python
    - setuptools
  run:
    - docutils
    - jedi
    - pycodestyle
    - pyflakes
    - pyqode.core
    - pyqode.qt
    - python
    - setuptools

test:
  imports:
    - pyqode
    - pyqode.python
    - pyqode.python._forms
    - pyqode.python.backend
    - pyqode.python.managers
    - pyqode.python.modes
    - pyqode.python.panels
    - pyqode.python.widgets
  requires:
    - pyqt

about:
  home: https://github.com/pyQode/pyqode.python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Adds python support to pyqode.core
  doc_url: https://github.com/pyQode/pyQode/wiki
  dev_url: https://github.com/pyQode/pyQode

extra:
  recipe-maintainers:
    - ericpre
