package:
  name: requests-oauthlib
  version: "0.6.2"

source:
  git_rev: v0.6.2
  git_url: https://github.com/requests/requests-oauthlib

#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - requests-oauthlib = requests-oauthlib:main
    #
    # Would create an entry point called requests-oauthlib that calls requests-oauthlib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - oauthlib >=0.6.2
    - requests >=2.0.0

  run:
    - python
    - oauthlib >=0.6.2
    - requests >=2.0.0

test:
  # Python imports
  imports:
    - requests_oauthlib
    - requests_oauthlib.compliance_fixes

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - requests-mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/requests/requests-oauthlib
  license: BSD License
  summary: 'OAuthlib authentication support for Requests.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
