{% set name = "pyqode.core" %}
{% set version = "2.14.0a4" %}
{% set sha256 = "48f0a61f9fe6145240aa61060bc54764edf800de3a28fbf68081353ffe3b30e1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://files.cogsci.nl/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  entry_points:
    - pyqode-console = pyqode.core.tools.console:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - future
    - pip
    - pygments
    - pyqode.qt
    - python
    - setuptools
  run:
    - future
    - pygments
    - pyqode.qt
    - python
    - setuptools

test:
  imports:
    - pyqode
    - pyqode.core
    - pyqode.core._designer_plugins
    - pyqode.core._forms
    - pyqode.core.api
    - pyqode.core.backend
    - pyqode.core.dialogs
    - pyqode.core.managers
    - pyqode.core.modes
    - pyqode.core.panels
    - pyqode.core.styles
    - pyqode.core.tools
    - pyqode.core.widgets
  commands:
    - echo input > input.txt
    - pyqode-console < input.txt
  requires:
    - pyqt

about:
  home: https://github.com/pyQode/pyqode.core
  license: MIT
  license_family: MIT
  summary: PyQt/PySide Source Code Editor Widget
  doc_url: https://github.com/pyQode/pyQode/wiki
  dev_url: https://github.com/pyQode/pyQode

extra:
  recipe-maintainers:
    - ericpre
