package:
  name: opensesame-extension-osf
  version: "1.0.9"

source:
  git_rev: v1.0.9
  git_url: https://github.com/dschreij/opensesame-extension-osf.git

build:
  noarch_python: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-opensesame

  run:
    - python
    - python-opensesame
    - python-qosf

about:
  home: https://github.com/dschreij/opensesame-extension-osf
  license: Apache Software License
  summary: 'OpenSesame OSF extension'
