{% set name = "python-opensesame" %}
{% set version = "3.3.0a57" %}
{% set sha256 = "12349f09047718ede14a28d28ddec7aaceec91605979b121fc76d38a5c8645de" %}
{% set url = "https://files.pythonhosted.org/packages/9a/20/e600a9e56dfbce6c98a5a34bdcfedef1f00dd014ea732a224d04df6d54a7/python-opensesame-3.3.0a57.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.21
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - rapunzel
    - pyqode.core >=2.14.0a4
    - pyqode.python >=2.12.2a6

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
