{% set name = "python-opensesame" %}
{% set version = "3.3.0a64" %}
{% set sha256 = "f1c933f847c76439b790cb107efc4acf366cc1a7e9c37a366feec3766755ae04" %}
{% set url = "https://files.pythonhosted.org/packages/e3/3f/e9bce1fc93fd6dafe259c1ee7e9dd064da67b693339a17b9b537173bd326/python-opensesame-3.3.0a64.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.21
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.14.0a4
    - pyqode.python >=2.12.2a6

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
