{% set name = "python-opensesame" %}
{% set version = "3.3.0a47" %}
{% set sha256 = "37dfccae37089c60ff6eb2d5d83154fc2309d0182474f7b13f2b02e1d7ed7046" %}
{% set url = "https://files.pythonhosted.org/packages/01/d4/3e01d5d6c6fb2b550850d15554c511fc3c5c1958204b722894b8c66bc185/python-opensesame-3.3.0a47.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.20
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.14.0a1
    - pyqode.python >=2.12.2a6

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
