{% set name = "python-opensesame" %}
{% set version = "3.3.3a1" %}
{% set sha256 = "16b55b47081f1735b52f2fcef3b8493e1c473c120268ef565fd5b01955443ba2" %}
{% set url = "https://files.pythonhosted.org/packages/7d/34/6033544237ff78171e1330d0d20c5c886bc4f45299dc306125805f5e4393/python-opensesame-3.3.3a1.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.24
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.15.0a4
    - pyqode.python >=2.12.2a10

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
