package:
  name: python-opensesame
  version: "3.2.0a31"

source:
  fn: python-opensesame-3.2.0a31.tar.gz
  url: https://pypi.python.org/packages/bb/d7/9637749d4615e03819cab14457fb6c6db321b55ffad2f31506b55f5371e2/python-opensesame-3.2.0a31.tar.gz
  md5: 229e27d814bdaf5fc3e98d7f4b69a2fa

build:
  noarch_python: True
  # preserve_egg_dir: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications

  run:
    - python
    - pyqt
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

# If the app key is present, the package will be an app, meaning it will
# appear in the Anaconda launcher.
app:
  # The command that is called to launch the app
  entry: opensesame
  # Icon file contained in the recipe
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
  # If own_environment is true, installing the app through the launcher
  # will install into its own environment. The default is false.
  # own_environment: true

