{% set name = "python-opensesame" %}
{% set version = "3.3.0a29" %}
{% set sha256 = "1849fd19d92a2fb2fb314ccea35c8c84c34e8fa66a3ff66b5d4a3ec8cd5f44db" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/ee/7d/f905ec080ab0089b4ebcce3bd9f54c2daa437f88b06c1bbc6e2b40aa60b9/{{ name }}-{{ version}}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-datamatrix
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyqode.core >=2.13.0a1
    - pyqode.python >=2.12.2a3

  run:
    - python
    - pyqt
    - python-datamatrix
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pyqode.core >=2.13.0a1
    - pyqode.python >=2.12.2a3

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
