package:
  name: python-opensesame
  version: "3.1.8a1"

source:
  fn: python-opensesame-3.1.8a1.tar.gz
  url: https://pypi.python.org/packages/83/07/7c320ddbcd2f4755a26771084cba0ad62cfbfc1c23a726ffa3569e042fcb/python-opensesame-3.1.8a1.tar.gz
  md5: c52005c175a3d6d9f07c946a851afc37

build:
  noarch_python: True
  # preserve_egg_dir: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications

  run:
    - python
    - pyqt
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

# If the app key is present, the package will be an app, meaning it will
# appear in the Anaconda launcher.
app:
  # The command that is called to launch the app
  entry: opensesame
  # Icon file contained in the recipe
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
  # If own_environment is true, installing the app through the launcher
  # will install into its own environment. The default is false.
  # own_environment: true

