{% set name = "python-opensesame" %}
{% set version = "3.3.2" %}
{% set sha256 = "52659165f2401e7fa7cc084f79c20b645efe140a20ec9765ba56791da8e5ab90" %}
{% set url = "https://files.pythonhosted.org/packages/51/1d/6e7e344922cf0081faa64e0a02ac4f7645fef9482dc24fb14875dad9b9fe/python-opensesame-3.3.2.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.24
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.15.0a4
    - pyqode.python >=2.12.2a10

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
