{% set name = "python-opensesame" %}
{% set version = "3.3.0a58" %}
{% set sha256 = "def529c015c45dd948d5986c5a71002fb3855debaf328eb25a1150f200622df1" %}
{% set url = "https://files.pythonhosted.org/packages/28/74/8278b0147025e6b54fd15bd6a2ec72d0062be07f592083cf3dcd41d3083a/python-opensesame-3.3.0a58.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.21
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - rapunzel
    - pyqode.core >=2.14.0a4
    - pyqode.python >=2.12.2a6

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
