{% set name = "python-opensesame" %}
{% set version = "3.3.0a38" %}
{% set sha256 = "9dd8fcf1f6ca77e6648c77bd2eb5ad1472a8111df4c5f88d7206543bcdb66107" %}
{% set url = "https://files.pythonhosted.org/packages/d5/c4/9ca35dc0110ee78efe3f16860bd5e72db880a190f5c66fb92ff40b65f9c5/python-opensesame-3.3.0a38.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.20
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.13.0a2
    - pyqode.python >=2.12.2a3

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
