{% set name = "python-opensesame" %}
{% set version = "3.3.0a66" %}
{% set sha256 = "bb334ea37df2a566a56eddd151de50fdd1c2ad0ae37a457afad37d5e7e9046d2" %}
{% set url = "https://files.pythonhosted.org/packages/0f/70/4f49dba0405607ae41a2615993d9a488f9158a79405aaa722ff53bc7c61e/python-opensesame-3.3.0a66.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.21
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.14.0a4
    - pyqode.python >=2.12.2a6

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
