package:
  name: python-opensesame
  version: "3.2.1"

source:
  fn: python-opensesame-3.2.1.tar.gz
  url: https://pypi.python.org/packages/2e/bf/3a83d887a0b280ebd0321a1af2ee1219a6ba8caa4dbbe79128a1a22b5b1b/python-opensesame-3.2.1.tar.gz
  md5: 3282bd59dbd03aac82b49cf3bfc21dca

build:
  noarch_python: True
  # preserve_egg_dir: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications

  run:
    - python
    - pyqt
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

# If the app key is present, the package will be an app, meaning it will
# appear in the Anaconda launcher.
app:
  # The command that is called to launch the app
  entry: opensesame
  # Icon file contained in the recipe
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
  # If own_environment is true, installing the app through the launcher
  # will install into its own environment. The default is false.
  # own_environment: true

