{% set name = "python-opensesame" %}
{% set version = "3.3.0a40" %}
{% set sha256 = "eab99522498c5230d5df5e934cb30223d9d5c7ba9b802e470c5eaf1337a46d90" %}
{% set url = "https://files.pythonhosted.org/packages/0d/7b/ca122ad299792a6d957cc3eec76e43407efec0c87b0d095027c0af33728a/python-opensesame-3.3.0a40.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.20
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.13.0a2
    - pyqode.python >=2.12.2a3

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
