package:
  name: python-opensesame
  version: "3.1.8"

source:
  fn: python-opensesame-3.1.8.tar.gz
  url: https://pypi.python.org/packages/b7/d8/c87e9439b893494a7d68c1385dc95f162bf6e4cbd0cd138532873f3cf236/python-opensesame-3.1.8.tar.gz
  md5: d3209d73a13cd8db19dbbfad254ab9e1

build:
  noarch_python: True
  # preserve_egg_dir: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - webcolors
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications

  run:
    - python
    - pyqt
    - python-qprogedit
    - python-qdatamatrix
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

# If the app key is present, the package will be an app, meaning it will
# appear in the Anaconda launcher.
app:
  # The command that is called to launch the app
  entry: opensesame
  # Icon file contained in the recipe
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
  # If own_environment is true, installing the app through the launcher
  # will install into its own environment. The default is false.
  # own_environment: true

