{% set name = "python-opensesame" %}
{% set version = "3.3.0a43" %}
{% set sha256 = "d5f5ca6fc0733599f6734e2e3414a94356678427b888e77112ea21da98a91b41" %}
{% set url = "https://files.pythonhosted.org/packages/4d/4a/e6992f8ab256cc3ca8677b64bcb2e41da38c4b9a7bbec119fb64cda2cc30/python-opensesame-3.3.0a43.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.20
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.13.0a2
    - pyqode.python >=2.12.2a3

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
