{% set name = "python-opensesame" %}
{% set version = "3.3.0a35" %}
{% set sha256 = "5716dbc9c95fe99860677d926760325929cc849006f9b834424f834265f51145" %}
{% set url = "https://files.pythonhosted.org/packages/38/f3/bb20c40779657a3e0926939f030fd8d274ca5f8d1d2fea9bde7fe2c97368/python-opensesame-3.3.0a35.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyqt
    - python-qdatamatrix >=0.1.20
    - python-pseudorandom
    - python-fileinspector
    - python-qnotifications
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core >=2.13.0a2
    - pyqode.python >=2.12.2a3

about:
  home: https://github.com/smathot/OpenSesame
  license: GNU General Public License v3 (GPLv3)
  summary: 'Graphical experiment builder for the social sciences'

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'
