{% set name = "pyspellchecker" %}
{% set version = "0.5.4" %}
{% set sha256 = "87075048d61ca971fa9f4fbcc23ca6755cef9844a15a81bd2bf9637ca3914da7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/36/d7/f5ffdb9ab4d458fae8be05ad5aeaaaae6a8600a7e83d732b06263f3bb8ab/pyspellchecker-0.5.4.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 1
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
  run:
    - python


about:
  home: https://github.com/barrust/pyspellchecker
  license: MIT License
  summary: 'Pure python spell checker based on work by Peter Norvig'
