{% set name = "python-qdatamatrix" %}
{% set version = "0.1.24" %}
{% set sha256 = "05c2f62cb410b876135c1614f67c74000dadff2d61f3d65b49931ebc97f6f828" %}
{% set url = "https://files.pythonhosted.org/packages/4b/6d/43ac6fc2cafd8e5f9846ab619df92e7b20b7f51373a7c16c24d8099f5f61/python-qdatamatrix-0.1.24.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 6

requirements:
  build:
    - python=3.6.4=0
    - setuptools
    - qtpy=1.4.0
    - pyqt
    - python-datamatrix

  run:
    - python
    - qtpy
    - pyqt
    - python-datamatrix

test:
  imports:
    - qdatamatrix

about:
  home: https://github.com/smathot/python-qdatamatrix
  license: GNU General Public License v3 (GPLv3)
  summary: 'A PyQt4/PyQt5 widget for viewing and editing a DataMatrix object.'
