package:
  name: python-qdatamatrix
  version: "0.1.17"

source:
  git_rev: release/0.1.17
  git_url: https://github.com/smathot/python-qdatamatrix.git

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-pseudorandom = python-pseudorandom:main
    #
    # Would create an entry point called python-pseudorandom that calls python-pseudorandom.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - qtpy
    - pyqt
    - python-datamatrix

  run:
    - python
    - qtpy
    - pyqt
    - python-datamatrix

test:
  # Python imports
  imports:
    - qdatamatrix

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/smathot/python-qdatamatrix
  license: GNU General Public License v3 (GPLv3)
  license_file: copyright
  summary: 'A PyQt4/PyQt5 widget for viewing and editing a DataMatrix object.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
