{% set name = "python-qdatamatrix" %}
{% set version = "0.1.22" %}
{% set sha256 = "efa00b89da6f313ed0d406f48391ff3f520ff6198f87ad271597d22c2cc604fa" %}
{% set url = "https://files.pythonhosted.org/packages/40/ad/7c7b34fd9ea6051e353ca805e829c6a76b13bbd9ad24cd416d9c505cef16/python-qdatamatrix-0.1.22.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 6

requirements:
  build:
    - python
    - setuptools
    - qtpy
    - pyqt
    - python-datamatrix

  run:
    - python
    - qtpy
    - pyqt
    - python-datamatrix

test:
  imports:
    - qdatamatrix

about:
  home: https://github.com/smathot/python-qdatamatrix
  license: GNU General Public License v3 (GPLv3)
  summary: 'A PyQt4/PyQt5 widget for viewing and editing a DataMatrix object.'
