{% set name = "python-qdatamatrix" %}
{% set version = "0.1.27" %}
{% set sha256 = "524dc171b7da58215b0c3dfd9bd91de1c1d998590e4ba3b44df24bf8b1dcc9db" %}
{% set url = "https://files.pythonhosted.org/packages/f7/d4/62a9be0d987aa393fad73ba84cd994af76698c4f792f307660681a15f7de/python-qdatamatrix-0.1.27.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  ignore_run_exports:
    - python_abi
    - qtpy
    - pyqt

requirements:
  build:
    - python=3.6.4=0
    - setuptools
    - qtpy=1.4.0
    - pyqt
    - python-datamatrix

  run:
    - python
    - qtpy
    - pyqt
    - python-datamatrix

test:
  imports:
    - qdatamatrix

about:
  home: https://github.com/smathot/python-qdatamatrix
  license: GNU General Public License v3 (GPLv3)
  summary: 'A PyQt4/PyQt5 widget for viewing and editing a DataMatrix object.'
