{% set name = "python-datamatrix" %}
{% set version = "0.10.17" %}
{% set sha256 = "f67e97f99172f133bce076b4a09d536e9b1bb5128afaa8dfe0a9c591b21099d7" %}
{% set url = "https://files.pythonhosted.org/packages/1d/97/d713dd4a7cbf1b5de3c88dc4cee48d882b9fe378b34b34875b4e19159394/python-datamatrix-0.10.17.tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - openpyxl
    - fastnumbers
    - prettytable

test:
  # Python imports
  imports:
    - datamatrix
    - datamatrix._datamatrix
    - datamatrix.io
    - datamatrix.convert
    - datamatrix.operations
    - datamatrix.series
    - datamatrix.functional
  requires:
    - numpy
    - scipy

about:
  home: https://github.com/smathot/python-datamatrix
  license: GNU General Public License v3 (GPLv3)
  summary: 'An intuitive, Pythonic way to work with tabular data'
