{% set name = "opensesame-extension-osweb" %}
{% set version = "1.3.7.1" %}
{% set sha256 = "82a07f5231c205b152dce308587b23ecbcac0d3e1a380a7314a0fd897b8273d7" %}
{% set url = "https://files.pythonhosted.org/packages/fd/2d/febe351811ec5190ab84b83e71b73cf80d93465831ccda6c04ec47aaafa3/opensesame-extension-osweb-1.3.7.1.tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  ignore_run_exports:
    - python_abi  

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-opensesame
    - beautifulsoup4
    - js2py
    - pyjsparser

about:
  home: https://github.com/dschreij/{{ name }}
  license: GPLv3
  summary: 'Online runtime for OpenSesame experiment builder (osweb)'
