{% set name = "python-qosf" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/dschreij/QOpenScienceFramework

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python=3.6.4=0
    - setuptools
    - qtpy=1.4.0
    - qt
    - pyqt
    - qtawesome
    - arrow
    - humanize
    - requests-oauthlib
    - python-fileinspector

  run:
    - python
    - qtpy
    - qt
    - pyqt
    - qtawesome
    - arrow
    - humanize
    - python-fileinspector
    - requests-oauthlib

test:
#  #Python imports
  imports:
    - QOpenScienceFramework

about:
  home: https://github.com/dschreij/QOpenScienceFramework
  license: Apache Software License
  license_file: copyright
  summary: 'PyQt widgets for working with the Open Science Framework API'
