package:
  name: python-qosf
  version: "1.1.4"

source:
  git_rev: v1.1.4
  git_url: https://github.com/dschreij/QOpenScienceFramework

build:
  noarch_python: True
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - qtpy
    - qt
    - pyqt
    - qtawesome
    - arrow
    - humanize
    - requests-oauthlib
    - python-fileinspector

  run:
    - python
    - qtpy
    - qt
    - pyqt
    - qtawesome
    - arrow
    - humanize
    - python-fileinspector
    - requests-oauthlib

test:
#  #Python imports
  imports:
    - QOpenScienceFramework

about:
  home: https://github.com/dschreij/QOpenScienceFramework
  license: Apache Software License
  license_file: copyright
  summary: 'PyQt widgets for working with the Open Science Framework API'
