{% set name = "python-qosf" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "c737b55dfded5576ccda10c905dcb28715123f625be006dc6b09dfeb8795eaee"

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python=3.6.4=0
    - setuptools
    - qtpy=1.4.0
    - qt
    - pyqt
    - qtawesome
    - arrow
    - humanize
    - python-fileinspector
    - requests-oauthlib

  run:
    - python
    - qtpy
    - qt
    - pyqt
    - qtawesome
    - arrow
    - humanize
    - python-fileinspector
    - requests-oauthlib

test:
#  #Python imports
  imports:
    - QOpenScienceFramework

about:
  home: https://github.com/dschreij/QOpenScienceFramework
  license: Apache Software License
  summary: 'PyQt widgets for working with the Open Science Framework API'
